### ISSUE TITLE
Cannot search Whois

### ISSUE THREAD

**Issue by Thomas0921** [bhavsec/reconspider#17]
**Describe the bug**
Cannot search whois, picture attacted below
I can see few errors while installation, could you explain what is it please :)?
`writing manifest file 'ReconSpider.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
warning: install_lib: 'build\lib' does not exist -- no Python modules to install`
`Installed d:\program files\python\lib\site-packages\click_plugins-1.1.1-py3.7.egg
error: The 'click' distribution was not found and is required by shodan`

**To Reproduce**
1. Follow the installation in documentation

**Expected behavior**
Whois data will be shown below

**Screenshots**
![image](https://user-images.githubusercontent.com/22499387/61369745-5e8e8b80-a8c3-11e9-8554-6b2a2c929c34.png)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [10]

**Comment by pburkart** [comment]
Hi there, I realize this issue is quite old, but I was wondering if you were still having issues with this. When you installed the requirements were you in the reconspider directory?

**Comment by Aravindha1234u** [comment]
You have update api values in required files. 
* Do check the update [V1.0.6 Beta](https://github.com/bhavsec/reconspider/releases/tag/1.0.6)
