### ISSUE TITLE
tool to consider

### ISSUE THREAD

**Issue by Luci-d** [bhavsec/reconspider#19]
**Is your feature request related to a problem? Please describe.**
info gathering is a bit slow, plus sometimes i face bugs with whois.

**Describe the solution you'd like**
You could use spyse API for most searches like DNS, IP, Port, Whois etc...

**Additional context**
They regularly scan the web and add all the data to own DB so you don't need to wait for the results. 

i hope it will help

**Comment by bhavsec** [comment]
This issue is now resolved. Try new update.

**Comment by Luci-d** [comment]
Cool thanks. will try
