### ISSUE TITLE
can anyone tell about how to get information using social accounts 

### ISSUE THREAD

**Issue by hunter7506** [bhavsec/reconspider#23]
1.Facebook 
2.Twitter 
3.Instagram

Username >> 3
choice >> 
 what to type in choice the username of accounts or the link ? please help

**Comment by Aravindha1234u** [comment]
**Usage of Social Media**

```
1.Facebook
2.Twitter
3.Instagram

Username >> Aravindha_Hariharan
choice >>3
```
You need to mention the username followed by which social media you need to check as mentioned above.
