### ISSUE TITLE
Grammar, Spelling, and Formatting need improvement

### ISSUE THREAD

**Issue by pburkart** [bhavsec/reconspider#24]
Looking through this repository I've noticed that there are quite a few issues with the grammar, spelling, and formatting of various features. Anyone fluent in English who is up to the task should spend sometime reading over the files to improve them. I intend to work more on this repository in that direction in the future. Please see my latest pull request for an example.

**Comment by Aravindha1234u** [comment]
Oh, Thank you we will look into it.
