### ISSUE TITLE
Error when using Phone Number option

### ISSUE THREAD

**Issue by TamojitSaha** [bhavsec/reconspider#27]
**Describe the bug**
Error when using Phone Number option

**To Reproduce**
1. Run `python3 reconspider.py`
2. Input '3' when prompted
3. Input the phone number - `PHONE NUMBER (919485247632) >> 919485247632`
4. See error :
```
Reconspider >> 3
PHONE NUMBER (919485247632) >> 919485247632
[+] Fetching Phonenumber Details...

Traceback (most recent call last):
  File "reconspider.py", line 39, in <module>
    from core import repl_prompt
  File "/root/reconspider/core/__init__.py", line 1, in <module>
    from .repl_prompt import *
  File "/root/reconspider/core/repl_prompt.py", line 153, in <module>
    repl()
  File "/root/reconspider/core/repl_prompt.py", line 64, in repl
    Phonenumber(ph)
  File "/root/reconspider/plugins/Phonenumber.py", line 17, in Phonenumber
    print("Number: "+get['number'])
KeyError: 'number'
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Terminal

**Comment by Aravindha1234u** [comment]
Thank you for reporting the issues. We are looking forward to it.

**Comment by Aravindha1234u** [comment]
We have updated on this Issue kindly pull or clone the repository so that updates are made.

**Comment by Aravindha1234u** [comment]
We have fixed this issue and a new commit has been done. Pull it from the repository or run an updated and check again if you face again issue. Please do let us know

https://github.com/bhavsec/reconspider/commit/e9f76844d75eee6f27630df1d90b8ea622d7f671
