### ISSUE TITLE
error using Phone number option

### ISSUE THREAD

**Issue by srkadia** [bhavsec/reconspider#29]
When using phone number option,
Program Terminates when the user enters a number

Traceback (most recent call last):
  File "reconspider.py", line 39, in <module>
    from core import repl_prompt
  File "/home/srk/Tools/Osint/reconspider/core/__init__.py", line 1, in <module>
    from .repl_prompt import *
  File "/home/srk/Tools/Osint/reconspider/core/repl_prompt.py", line 153, in <module>
    repl()
  File "/home/srk/Tools/Osint/reconspider/core/repl_prompt.py", line 64, in repl
    Phonenumber(ph)
  File "/home/srk/Tools/Osint/reconspider/plugins/Phonenumber.py", line 17, in Phonenumber
    print("Number: "+get['number'])
KeyError: 'number'

**Comment by Aravindha1234u** [comment]
We have updated on this Issue kindly pull or clone the repository so that updates are made.

**Comment by Aravindha1234u** [comment]
We have fixed this issue and a new commit has been done. Pull it from the repository or run an updated and check again if you face again issue. Please do let us know

https://github.com/bhavsec/reconspider/commit/e9f76844d75eee6f27630df1d90b8ea622d7f671

**Comment by Anonymous-srk** [comment]
Can you explain to me this

In phone number option,
Your monthly usage limit has been reached

**Comment by Anonymous-srk** [comment]
but, how many people use this tool, I mean per month only 250 requests is
unfair

**Comment by Aravindha1234u** [comment]
Bro These are paid API and we get only 250 requests per month. If you want you can replace the API keys of ours with yours and you can still use the tool without any problem. we will try to bring an update on this without API key for sure. Stay Tuned.
