### ISSUE TITLE
[Request] pip package

### ISSUE THREAD

**Issue by zero77** [bhavsec/reconspider#32]
**Is your feature request related to a problem? Please describe.**
Not really a problem but, it would make reconspider more accessible.
Also, it makes reconspider easier to install and keep upto date.Can you please provide a pip 

**Describe the solution you'd like**
Can you please provide a pip package.

**Describe alternatives you've considered**

**Additional context**

**Comment by bhavsec** [comment]
Make sure you are using Python 3 and follow the installation procedure via setup.py from README.md.
