### ISSUE TITLE
Install setup.py: PyPi.rst no such file

### ISSUE THREAD

**Issue by RizzoRavier** [bhavsec/reconspider#34]
While trying to install setup.py I am met with this error
pi@raspberrypi:~/reconspider $ sudo python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'console'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing requirements to ReconSpider.egg-info/requires.txt
writing ReconSpider.egg-info/PKG-INFO
writing top-level names to ReconSpider.egg-info/top_level.txt
writing dependency_links to ReconSpider.egg-info/dependency_links.txt
reading manifest file 'ReconSpider.egg-info/SOURCES.txt'
writing manifest file 'ReconSpider.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
warning: install_lib: 'build/lib.linux-armv7l-2.7' does not exist -- no Python modules to install

creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying ReconSpider.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying ReconSpider.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying ReconSpider.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying ReconSpider.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying ReconSpider.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/ReconSpider-1.0.5-py2.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing ReconSpider-1.0.5-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/ReconSpider-1.0.5-py2.7.egg
Copying ReconSpider-1.0.5-py2.7.egg to /usr/local/lib/python2.7/dist-packages
ReconSpider 1.0.5 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/ReconSpider-1.0.5-py2.7.egg
Processing dependencies for ReconSpider==1.0.5
Searching for h8mail
Reading https://pypi.org/simple/h8mail/
Downloading https://files.pythonhosted.org/packages/e7/91/27a978ec885c703364bf485320c16a0a0a0970462ed43af764e466f29c44/h8mail-2.5.4.tar.gz#sha256=9f7b5d8d040f07a41bf0495bf0129672af235bdc27ab941c16ea5552913d5273
Best match: h8mail 2.5.4
Processing h8mail-2.5.4.tar.gz
Writing /tmp/easy_install-TA4en1/h8mail-2.5.4/setup.cfg
Running h8mail-2.5.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-TA4en1/h8mail-2.5.4/egg-dist-tmp-vJcMoh
error: [Errno 2] No such file or directory: 'PyPi.rst'

Help please

**Comment by bhavsec** [comment]
ReconSpider is not compatible with ARM devices currently. But in future updates we'll try to work on it.
