### ISSUE TITLE
Requirements.txt is not found

### ISSUE THREAD

**Issue by DR3DL0RD** [bhavsec/reconspider#37]
**Describe the bug**
once install runs it seems to run into the error of 'requirements.txt is not found'

**To Reproduce**
1. git clone it
2. run the install.py
3. See error

**Expected behavior**
requirements.txt to be found

**Screenshots**
![image](https://user-images.githubusercontent.com/61581417/94783952-fa1ef580-03bc-11eb-8a02-3c497e11f5a0.png)

**Desktop (please complete the following information):**
 - OS: ParrotOS (up to date)
 - Browser: Firefox
 - Version: latest

**Comment by djhashh** [comment]
ditto

**Comment by bhavsec** [comment]
Make sure you are using Python 3 and follow the installation procedure via setup.py from README.md.
