### ISSUE TITLE
Domian choice could not choose PORT and repeat again and again

### ISSUE THREAD

**Issue by WAY29** [bhavsec/reconspider#39]
**Describe the bug**
Domian choice could not choose PORT and repeat again and again

**To Reproduce**
1. start reconspider
2. Choose 2
3. Input Domain
4. Input Port, My input is 80
4. Invalid port - Available(80,443)

**Screenshots**
![image](https://user-images.githubusercontent.com/41830147/96356022-a2ea8600-111b-11eb-95ad-5f8287df6994.png)

**Desktop (please complete the following information):**
 - OS: WSL
 - Browser Chrome
 - Version Latest

**Additional context**
I try to slove by this:
![image](https://user-images.githubusercontent.com/41830147/96356030-bd246400-111b-11eb-9bdc-87ea6fc0899f.png)

**Comment by bhavsec** [comment]
Thanks for your contribution. This Issue has been fixed in ReconSpider version 1.0.7
