### ISSUE TITLE
no module named 'pip'

### ISSUE THREAD

**Issue by SupremeERG** [bhavsec/reconspider#44]
When running the installation I get to the command "sudo python setup.py install"
Once I run this command I get this error:
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import pip
ImportError: No module named pip
Anyone know a fix?

**Comment by madhu143maddy** [comment]
i have also the same issue 
can anyone solve ?

**Comment by Andycko** [comment]
If you have python 2 and python 3 installed at the same time, you might need to set pip as your default package manager for python 2.

`python2.7 -m ensurepip --default-pip`

Source: https://stackoverflow.com/a/46631019
