### ISSUE TITLE
Domain ports fails 

### ISSUE THREAD

**Issue by azzarin** [bhavsec/reconspider#47]
**Describe the bug**
Port unavaible: 443
Reconspider >> 2
HOST (URL / IP) >> nor3d.no
PORT >> 443
Invalid port - Available(80,443)
HOST (URL / IP) >> 

**To Reproduce**
Reconspider >> 2
HOST (URL / IP) >> nor3d.no
PORT >> 443
Invalid port - Available(80,443)
HOST (URL / IP) >> 

**Desktop (please complete the following information):**
 - OS: Kali Linux 
 - 5.10.0-kali7-amd64 #1 SMP Debian 5.10.28-1kali1 (2021-04-12) x86_64 GNU/Linux
Python 3.9.2

**Comment by tobalo** [comment]
commenting to follow

**Comment by bhavsec** [comment]
This Issue has been fixed in ReconSpider version 1.0.7
