### ISSUE TITLE
installing issue     

### ISSUE THREAD

**Issue by Mrunknownrs** [bhavsec/reconspider#49]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
While installing showing the wheel package is not available

**Comment by Mrunknownrs** [comment]
![Screenshot_2021-08-11-17-13-34-896_com termux](https://user-images.githubusercontent.com/88764246/129023355-dd3997a7-05ab-4036-a244-a5e5a313ad09.jpg)

This is the isssue im facing

**Comment by bhavsec** [comment]
ReconSpider is mostly compatible with Computers. It's not yet fully supported by Termux (Mobile Platforms).
