### ISSUE TITLE
Anomalous backslash in string: '\_'. String constant might be missing an r prefix.

### ISSUE THREAD

**Issue by 4ROR4** [bhavsec/reconspider#5]
File: [reconspider.py](https://github.com/bhavsec/reconspider/blob/master/reconspider.py)

Line: 6

Error: Anomalous backslash in string: '\_'. String constant might be missing an r prefix.

**Comment by pburkart** [comment]
Not sure if this is an ongoing issue but I've submitted a pull request which should hopefully fix this issue.

**Comment by Aravindha1234u** [comment]
Check the New [1.0.6 V](https://github.com/bhavsec/reconspider/releases/tag/1.0.6)
